# Generated by Django 3.2.5 on 2021-08-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secret', models.UUIDField(default=uuid.uuid4)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('skin_type', models.CharField(choices=[('건성', '건성'), ('지성', '지성'), ('복합성', '복합성'), ('중성', '중성')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=20)),
                ('board_contents', models.TextField()),
                ('board_views', models.PositiveSmallIntegerField(default=0)),
                ('board_create_at', models.DateTimeField(auto_now_add=True)),
                ('board_type', models.CharField(choices=[('건성', '건성'), ('지성', '지성'), ('복합성', '복합성'), ('헤어/뷰티', '헤어/뷰티'), ('스타일', '스타일')], max_length=255)),
                ('board_like', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-board_create_at'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=300)),
                ('product_url', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('선케어', '선케어'), ('스킨케어', '스킨케어'), ('색조화장', '색조화장'), ('향수', '향수')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
